version: "3.8"

services:
  mcp-server-http:
    build:
      context: .
      dockerfile: Dockerfile.http
    container_name: mcp-server-http
    ports:
      - "4445:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
